version: '3.9'

services:
  db:
    image: mysql:8.4
    container_name: mysql_db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
     - ./mysql:/var/lib/mysql
    

     
